### ISSUE TITLE
Node version errors in Actions

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#8]
Action runs are throwing errors ([example](https://github.com/stevekuznetsov/avalanche-forecast/actions/runs/3651928599)):
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2
```

The references to those actions reference Node 16: 
```yaml
      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
```
but that doesn't seem to be enough. maybe update to `actions/setup-node@v3`? 🤷‍♂️
